// Command correlate-duplicate-reports suggests duplicate links from a preselected issue shortlist.
// Requires TYPESAFE_API_KEY; run with: go run ./examples/go-software-use-cases/07-correlate-duplicate-reports
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/captain-corgi/typesafe-sdk-go"
)

type issue struct{ id, report string }

func main() {
	client, err := typesafe.NewClient()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer client.Close()
	incoming := issue{"BUG-204", "On SDK v1.4 in Windows CI, retrying a 429 waits zero seconds. Repro: run TestRetryBackoff."}
	// An exact title/tag index produced these candidates; issue IDs are never generated by Jev.
	candidates := []issue{
		{"BUG-177", "On SDK v1.4 in Windows CI, a 429 retry skips the expected delay. Repro: TestRetryBackoff."},
		{"BUG-190", "On SDK v1.3 on Linux, retries exceed the maximum attempt count in production."},
	}
	for _, candidate := range candidates {
		resp, err := client.SystemOne(context.Background(), &typesafe.SystemOneParams{
			State: map[string]any{"new_report": incoming.report, "candidate_report": candidate.report},
			Questions: typesafe.Questions{
				"match": typesafe.Score{Instructions: "How likely are these the same underlying bug?", Criteria: typesafe.ScoreCriteria{
					"Different bugs", "Possibly the same bug", "Same underlying bug",
				}},
				"symptoms":    typesafe.Noul{Instructions: "Do the described symptoms agree?"},
				"environment": typesafe.Noul{Instructions: "Do the described SDK version and environment agree?"},
				"repro":       typesafe.Noul{Instructions: "Do the described reproduction steps agree?"},
			},
		})
		if err != nil {
			fmt.Printf("%s vs %s: queue for review (%v)\n", incoming.id, candidate.id, err)
			continue
		}
		match, signals := resp.Scores()["match"], resp.Nouls()
		switch {
		case match.Confidence >= 0.75 && match.Score >= 1.6 && signals["symptoms"].Noul >= 0.75 && signals["environment"].Noul >= 0.75 && signals["repro"].Noul >= 0.75:
			fmt.Printf("%s: suggest duplicate link to %s; human confirms before merge\n", incoming.id, candidate.id)
		case match.Confidence >= 0.75 && match.Score < 0.5:
			fmt.Printf("%s vs %s: likely distinct\n", incoming.id, candidate.id)
		default:
			fmt.Printf("%s vs %s: queue ambiguous pair for review\n", incoming.id, candidate.id)
		}
	}
}
