// Command fuzz-seed-curation maps a bug report to a reviewed byte fixture.
// It prints an f.Add snippet for a developer; no fuzz target calls Jev.
package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"

	"github.com/captain-corgi/typesafe-sdk-go"
)

func main() {
	if os.Getenv("TYPESAFE_API_KEY") == "" {
		log.Fatal("set TYPESAFE_API_KEY for this opt-in corpus tool")
	}
	client, err := typesafe.NewClient()
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	report := "The parser crashes when a document contains a nested closing brace inside another group."
	// These are pre-reviewed parser inputs, not bytes generated by Jev.
	seeds := map[string][]byte{
		"empty_input":      {},
		"invalid_utf8":     {0xff, 0xfe},
		"nested_delimiter": []byte("{{value}}"),
		"oversized_field":  bytes.Repeat([]byte{'x'}, 1025),
	}
	resp, err := client.SystemOne(context.Background(), &typesafe.SystemOneParams{
		State: report,
		Questions: typesafe.Questions{"boundary": typesafe.Choice{
			Instructions: "Which known parser boundary does the report describe?",
			Criteria: typesafe.ChoiceCriteria{
				"empty_input": "No bytes supplied", "invalid_utf8": "Malformed UTF-8 input", "nested_delimiter": "Nested or repeated delimiters", "oversized_field": "Field beyond a size limit", "other": "None fits",
			},
		}},
	})
	if err != nil {
		fmt.Println("INCONCLUSIVE: design a seed manually;", err)
		return
	}
	a := resp.Choices()["boundary"]
	seed, ok := seeds[a.Choice]
	if !ok || a.Confidence < 0.85 {
		fmt.Printf("INCONCLUSIVE boundary (%s, %.2f): design a seed manually\n", a.Choice, a.Confidence)
		return
	}
	fmt.Printf("REVIEW seed %s (confidence %.2f): f.Add(%#v)\n", a.Choice, a.Confidence, seed)
	fmt.Println("Keep FuzzXxx assertions deterministic; retain all existing corpus inputs.")
}
