// Command version-contradictions compares two adjacent, immutable versions
// selected by SQL and proposes a conflict review row without changing history.
//
// Requires TYPESAFE_API_KEY; run with:
//
//	go run ./examples/relational-db-use-cases/version-contradictions
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/captain-corgi/typesafe-sdk-go"
)

const rubricVersion = "claim-conflict-v1"

func main() {
	if os.Getenv("TYPESAFE_API_KEY") == "" {
		log.Fatal("set TYPESAFE_API_KEY")
	}
	client, err := typesafe.NewClient()
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	// These rows share a stable record ID and were selected as adjacent
	// versions by tenant-scoped SQL; their IDs are never generated by Jev.
	tenantID, recordID := int64(42), int64(100)
	oldID, newID := int64(5001), int64(5002)
	oldText := "The appliance was installed in building A on 12 August."
	newText := "The appliance was installed in building B on 12 August."
	resp, err := client.SystemOne(context.Background(), &typesafe.SystemOneParams{
		State: map[string]any{"old_text": oldText, "new_text": newText},
		Questions: typesafe.Questions{
			"contradiction": typesafe.Noul{Instructions: "Does the newer text make an incompatible claim about the same fact? Added detail alone is not a contradiction.", Criteria: &typesafe.NoulCriteria{
				True: "Same fact is asserted with incompatible values", False: "Compatible detail or unrelated claims",
			}},
			"retraction": typesafe.Noul{Instructions: "Does the newer text explicitly retract or correct the older claim?", Criteria: &typesafe.NoulCriteria{
				True: "Explicit correction or retraction", False: "No explicit correction language",
			}},
		},
	})
	if err != nil {
		log.Fatalf("leave comparison unresolved; preserve both versions: %v", err)
	}
	contradiction := resp.Nouls()["contradiction"].Noul
	retraction := resp.Nouls()["retraction"].Noul
	fmt.Printf("contradiction %.2f; explicit retraction %.2f\n", contradiction, retraction)
	if contradiction < 0.90 || retraction > 0.10 { // Calibrate both gates on history pairs.
		fmt.Println("comparison unresolved or corrected; retain both immutable versions")
		return
	}
	// Insert only a review edge; reviewers or business rules determine the
	// current truth. An application transaction can bundle this with its audit.
	fmt.Printf("SQL: INSERT INTO version_conflicts (tenant_id, record_id, old_version_id, new_version_id, rubric_version, model_version, review_state) VALUES ($1, $2, $3, $4, $5, $6, 'pending') ON CONFLICT (old_version_id, new_version_id) DO NOTHING\nargs: %#v\n",
		[]any{tenantID, recordID, oldID, newID, rubricVersion, resp.Model})
}
